### ISSUE TITLE
2dcl option does not work as described in tutorial

### ISSUE THREAD

**Issue by tmombaecher** [gammacombo/gammacombo#103]
in the tutorial 4 (2D prob scan) the option --2dcl is introduced without an additional parameter.
When trying, it fails and tells, that it should come with an integer parameter value. 

If I pass 0, it acts like the option is not given,
if I pass 1 or 2 it does, what the manual says (print contours of 68% CL and 95% CL)

Suggestions: 1) remove the requirement of the integer value and implement as the manual demonstrates
2) give a meaning to the integer values (e.g. 0-> default, 1-> 1sigma, 2->2sigma,... for the innermost contour) and change manual accordingly

**Comment by KonstantinSchubert** [comment]
In OptParser.cpp, this arumgent is defined as a `TCLAP::MultiArg<int>`. https://github.com/gammacombo/gammacombo/blob/datasets_dev/core/src/OptParser.cpp#L568
I suppose that implementing it as a TCLAP::SwitchArg would be more in line with what the documentation says? 

@matthewkenzie Is there a particlular reason why `TCLAP::MultiArg<int>` was chosen?

**Comment by matthewkenzie** [comment]
Yes there is. The tutorial is out of date and should be updated. If you pass --2dcl 0 it will draw contours at 39% and 86% (i.e. where the equivalent 1D projection would be). If you pass --2dcl 1 it will draw contours at 68% and 95% (i.e. where the 1 and 2 sigma 2D contours are). The reason that this is not a SwitchArg is that it may depend on the combination. I.e. if you are drawing a 2D plot of A vs B which includes a measurement of only A and only B (a vertical and horizontal band) then you would require --2dcl 0 for both of these. If you then want to draw over the top a combined measurement of A and B this would require --2dcl 1. The tutorial should of course be updated.

**Comment by KonstantinSchubert** [comment]
Okay. I will try to update the manual and push it into the datasets_dev branch of the manual.

**Comment by KonstantinSchubert** [comment]
I replaced `--2dcl` with `--2dcl 1` everywhere in the PDF, I hope that fixes it. Will now read and try to understand why one needs to draw 39% confidence contours...
