### ISSUE TITLE
Add number of scan points to file name of pluginbatch output files

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#108]
I think that this applies to both the datasets stuff and the core stuff:

It would be nice to encode the number of scan points into the file name of the pluginbatch output file. This way, when calling `-a plugin`, we can make sure that we are not accidentally using a different number of scan points and we can print more informative error messages.

@tmombaecher and I already discussed this, but I would be interested in your opinion, @matthewkenzie

**Comment by matthewkenzie** [comment]
That is a good idea. It makes much more sense that -a plugin reads the number of points from the file and indeeds avoid any irritating conflicts. Can’t think of any reason off the top of my head why it would cause a problem.

**Comment by KonstantinSchubert** [comment]
Well, actually, the way it works for the Datasets is that the user is expected to pass the number of scan points as an option when doing the `-a plugin` command. 
But having it in the file name would allow to match between the passed number and the number in the file name - thus avoiding mistakes and supporting different numbers of scan points in parallel.

I noticed that for the normal Gammacombo, you do not need to pass the number of scan points when you call plugin:

```

**Comment by matthewkenzie** [comment]
You don’t have to. It’s an option though ( --npointstoy ). I think the default is 100.

**Comment by matthewkenzie** [comment]
This doesn't need to be in the name of the file but should simply be read from the first file that is read.
