### ISSUE TITLE
Fitting procedures and chi2 histograms

### ISSUE THREAD

**Issue by tmombaecher** [gammacombo/gammacombo#122]
This is a compatibility problem between the datasets and the combination part:

In the combination part, the fitting is done via `RooFitResult* Utils::fitToMin(RooAbsPdf *pdf, bool thorough, int printLevel)` (in https://github.com/gammacombo/gammacombo/blob/master/core/src/Utils.cpp), where AFAIK the fitting metric is changed to `-2log(likelihood)` and also somehow the global minimum of the fit is set to zero. 

In the datasets part, the fitting is done via the usual `RooAbsPdf->fitTo(RooDataset)` method, which uses the minimum negative loglikelihood as metric and does not correct wrt global minimum. In the scan2d case this minimum `chi2=2*MinNLL(fitresult)` from the fit is handed to the `hchi2min2d` histogram, which is drawn by the `OneMinusCLPlot2d::DrawFull()` method as a deltachi2. Thus it's wrong, because the global minimum doesn't get subtracted in this case.

We should adapt the fitting for the datasets part. But let's make sure to keep the fitting configurable (overridable) for the user.

**Comment by matthewkenzie** [comment]
Has this been resolved?

**Comment by tmombaecher** [comment]
unifying the fitting procedures is not that easy (especially if you want to keep the it configurable). But I am now working on making the `deltaChi2` plots comparable.

**Comment by tmombaecher** [comment]
Can be closed with #207, I think.
