### ISSUE TITLE
remove this->

### ISSUE THREAD

**Issue by tmombaecher** [gammacombo/gammacombo#136]
In many parts of the code we use `this->` as a reference to the class in which we are currently working. That is only necessary in very specific cases and should be removed wherever possible.

**Comment by matthewkenzie** [comment]
I'm not sure I agree necessarily. There are probably places where this is used and it shouldn't be however in some cases I think we do want to keep this as it is. For example we may want to use the inherited class implementation when we only have a pointer to the parent. 

For example a case like this:

```c++
MethodProbScan *probScan;
if (runOnDatasets) probScan = new MethodDatasetsProbScan(blah);
else probScan = new MethodProbScan(blah);
probScan->callSomeFunction();
```

Now it may be that when we look into the `callSomeFunction()` method it is only implemented in the parent `MethodProbScan` class however within that function we want to call another function which has a different implementation in the daughter class. So if we did that like this:

```c++
MethodProbScan::callSomeFunction(){
  callASecondFunction();
}
```

It will always call the version of `callASecondFunction()` implemented in `MethodProbScan`. However if we call like this:

```c++
MethodProbScan::callSomeFunction(){
  this->callASecondFunction();
}
```

then it will call the version of `callASecondFunction()` implemented in either `MethodProbScan` or `MethodDatasetsProbScan` depending on which object it is.

**Please lets be careful about changing this without really careful thought**

I propose closing this issue

**Comment by tmombaecher** [comment]
Ok, closing this. I was not aware of this, but you are right.
