### ISSUE TITLE
allow user specific CL

### ISSUE THREAD

**Issue by tmombaecher** [gammacombo/gammacombo#158]
As far as I know, we only calculate confidence intervals corresponding to 0.68%, 0.95% and 0.99% CL. For limit setting a 90% CL is not unusual. 

So why not have an option for a user specific CL (to be set on the command line)?

**Comment by matthewkenzie** [comment]
A good suggestion, could be comma separated or MultiArg as well

On 5 Sep 2017, at 13:43, Titus <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I know, we only calculate confidence intervals corresponding to 0.68%, 0.95% and 0.99% CL. For limit setting a 90% CL is not unusual.

So why not have an option for a user specific CL (to be set on the command line)?
