### ISSUE TITLE
Uncertainties on expected CLs (relevant for advanced interpolation)

### ISSUE THREAD

**Issue by fionnbishop** [gammacombo/gammacombo#210]
The uncertainties on hCLsExp appear to be the default, unlike the uncertainties on hCLsFreq, which are calculated explicitly. Presumably these incorrect uncertainties are used when fitting a pol2 to the expected points to perform interpolation. Would it be possible to put the correct uncertainties on this histogram?

**Comment by matthewkenzie** [comment]
Not sure I completely follow. Could you expand your point a bit (and maybe include some plots) to give me a better idea?

Would you class this as a "bug" or an "enhancement"?

If this is an additional feature you would like then please consider implementing it and making a pull request 😀

**Comment by tmombaecher** [comment]
I think I know: we compute also expected limits with the `--cls 2` method from the `hCLsExp` histogram. But while for e.g. the `hCLsFreq` we also calculate uncertainties, we don't for the `hCLsExp` (e.g. in https://github.com/gammacombo/gammacombo/blob/e0dd131f9f3f1f57012a6a184840ae6e7d470cbf/core/src/MethodDatasetsPluginScan.cpp#L747 and below).
This might have an effect on the interpolation for the calculation on the expected limits (though it's a minor thing).

It's easy to fix, I can do it this afternoon

**Comment by fionnbishop** [comment]
> 
> 
> I think I know: we compute also expected limits with the `--cls 2` method from the `hCLsExp` histogram. But while for e.g. the `hCLsFreq` we also calculate uncertainties, we don't for the `hCLsExp` (e.g. in
> 
> https://github.com/gammacombo/gammacombo/blob/e0dd131f9f3f1f57012a6a184840ae6e7d470cbf/core/src/MethodDatasetsPluginScan.cpp#L747
> and below).
> This might have an effect on the interpolation for the calculation on the expected limits (though it's a minor thing).
> 
> It's easy to fix, I can do it this afternoon

Yes, this is exactly what I'm referring to - Thanks for taking a look at it.

**Comment by tmombaecher** [comment]
I think we can close it with #211.
I propose to not add the error bars and keep the plotting style.

**Comment by tmombaecher** [comment]
Closing now. If there turns out to be still something fishy with this, feel free to reopen.

**Comment by fionnbishop** [comment]
Thanks for adding this. I agree that there is no need to add them to plots. I have however, noticed that the expected and observed CLs uncertainties differ significantly (both in how they are calculated and actual size of the uncertainties). I'm not confident on how they should be calculated, but the method for calculating the observed CLs makes more sense to me.

Observed (with hCLsFreq being the one which is plotted, I believe):
https://github.com/gammacombo/gammacombo/blob/1729e00a78dd7648a42bf51ec2f21c9e691d9daa/core/src/MethodDatasetsPluginScan.cpp#L678-L683
https://github.com/gammacombo/gammacombo/blob/1729e00a78dd7648a42bf51ec2f21c9e691d9daa/core/src/MethodDatasetsPluginScan.cpp#L799-L802

Expected:
https://github.com/gammacombo/gammacombo/blob/1729e00a78dd7648a42bf51ec2f21c9e691d9daa/core/src/MethodDatasetsPluginScan.cpp#L765-L766

**Comment by tmombaecher** [comment]
Do you have an example on how different they are? The computation of the errors of`hCLsFreq` cannot be easily adapted, as `quantiles_cls[2] != quantiles_clsb[2]/quantiles_clb[2]`. So the implementation I made was the closest to the truth I got in a quick implementation. But thinking about it this ignores the fact that the CLs values rely on the statistics of two independent distributions (`sampledSchi2Values` and `sampledBValues`) of equal size and not only one, so should be roughly a factor sqrt(2) larger (if it's simply that factor, it won't impact the interpolation).
Currently I don't have a bright idea on how to estimate the uncertainty better. Uncertainty estimates of quantiles are scarce in literature, I think.

**Comment by fionnbishop** [comment]
OK, I see what the problem is.
I have attached a couple of plots which show the size of uncertainties on observed and expected points. It is large at low poi for observed and small for expected, and generally much smaller for expected.
Would using the fractional uncertainty on quantiles_clsb[2]/quantiles_clb[2] be a reasonable approximation?
[expected_interp.pdf](https://github.com/gammacombo/gammacombo/files/4553041/expected_interp.pdf)
[observed_interp.pdf](https://github.com/gammacombo/gammacombo/files/4553042/observed_interp.pdf)

**Comment by tmombaecher** [comment]
Sorry for the delay, I was a bit busy with a conference. I find several things:
1) the error bars are not used for the interpolation (but could easily be implemented, will check)
2) I checked various uncertainty techniques and find actually the implemented method (`simple binomial error on cls dist`) being closest to the (quickly computationally expensive, but most correct) uncertainties from bootstrapping. See attached plot. I will try with more scan points and more toys as well as a cross check.
[median_error_test_20p_100t.pdf](https://github.com/gammacombo/gammacombo/files/4592110/median_error_test_20p_100t.pdf)

**Comment by tmombaecher** [comment]
I checked with more scan points
![median_error_test_100p_100t_2](https://user-images.githubusercontent.com/22791577/81547671-77998900-937c-11ea-9aef-108ea944671c.png)
and also more toys
![median_error_test_100p_1000t_2](https://user-images.githubusercontent.com/22791577/81547677-78cab600-937c-11ea-8b89-b44766a4ab70.png)
The result is not super conclusive. The only thing which is clear is that the fractional uncertainty of clsb and clb quantiles are completely wrong.
But reading my way through the various proposed solutions, each has its drawback (assumption of normal-like distribution, many toys, etc.) and the distributions we are dealing with are quite non-smooth. Even the bootstrapping method is not reliable apparently.
So I propose to stay with the binomial errors of the median cls value in #212, which gives a seemingly robust estimate.
In the end the gain is marginal, as the errors rather similar over the points that are used for interpolation.

In #212 I also added the error bars to be used in the interpolation fit, but only for the plugin method (in the prob method all points have equal weight, as they have no errors attached).

If @fionnbishop agrees (and @matthewkenzie ) I would "reclose" and merge #212, since that was her issue. Let me know whether the fitting is giving stable results. The fits can be accessed in a control plot now.

**Comment by tmombaecher** [comment]
One more thing: the errors on a median of a sample of measurements is expected to be smaller than the error on a single measurement

**Comment by fionnbishop** [comment]
Based on your findings, I agree that it is probably best to continue using the binomial error on CLs (and I realised since my last comment that the uncertainties on expected CLb and CLsb are not binomial anyway, since expected CLb is 0.5 by construction). But thank you for looking into this.

I will try out the updated fitting once the jobs I am currently running have finished, and let you know how it goes.

**Comment by fionnbishop** [comment]
These changes seem to work well.

**Comment by tmombaecher** [comment]
Ok, closing this then.
