### ISSUE TITLE
Installation on lxplus is broken

### ISSUE THREAD

**Issue by mreboud** [gammacombo/gammacombo#226]
The installation seems to be broken on Lxplus:

libgsl.so.19 is not found during the installation on Lxplus6 and 7.

This seems to be due to a Python2/3 mismatch in the execution of ```/cvmfs/sft.cern.ch/lcg/releases/LCG_88/lcgenv/1.3.3/x86_64-centos7-gcc62-dbg/lcgenv``` called by https://github.com/gammacombo/gammacombo/blob/development/scripts/setup_lxplus.sh.

**Comment by matthewkenzie** [comment]
Thanks for letting us know. Could you try using **just** the following instead of the two source commands:

```bash
source /cvmfs/sft.cern.ch/lcg/views/LCG_96bpython3/x86_64-centos7-gcc9-opt/setup.sh
```

**Comment by mreboud** [comment]
(it's building)

**Comment by matthewkenzie** [comment]
Did you do this from a fresh shell? It looks like it still wants to find the older version of ROOT

**Comment by tmombaecher** [comment]
@mreboud: can you just for safety check that my fix works? Before I merge? I just updated to LCG_98. 
I'm certainly no C++ pro, but for me that worked.

**Comment by mreboud** [comment]
hmm the error is different now :I have
```make[2]: ccache: Command not found```
```make[2]: *** [CMakeFiles/gammacomboCoreComponents.dir/core/src/CLIntervalMaker.cpp.o] Error 127```

**Comment by mreboud** [comment]
> Did you do this from a fresh shell? It looks like it still wants to find the older version of ROOT

Yes. I don't know why the old version of root is called at some point.

**Comment by matthewkenzie** [comment]
> hmm the error is different now :I have
> `make[2]: ccache: Command not found`
> `make[2]: *** [CMakeFiles/gammacomboCoreComponents.dir/core/src/CLIntervalMaker.cpp.o] Error 127`

Strange as the compile you check for ccache availability. You will need to completely clean the install before implementing @tmombaecher's fix. In fact this may be the issue you were seeing before (as cmake will have picked up what you tried to use before when compiling)

so I suggest (after getting @tmombaecher fix branch):
```bash
rm -rf build
mkdir build
cd build
make ..
make -j8 install
```

**Comment by tmombaecher** [comment]
> source /cvmfs/sft.cern.ch/lcg/views/LCG_96bpython3/x86_64-centos7-gcc9-opt/setup.sh

I tried also this idea. It compiles (cleaning the full `build` directory before), but throws very weird errors at runtime for the dataset case. My fix however works. I'll still wait for @mreboud to confirm my fix (with a cleaning of the full `build`directory) before merging.

**Comment by mreboud** [comment]
Sorry for the delay.
The fix works with the clean directory (I though make clean would be enough). Everything compiles without errors.
Thank you both for your answers.
