### ISSUE TITLE
Decimal place rounding

### ISSUE THREAD

**Issue by pronitron** [gammacombo/gammacombo#231]
Hi,

Currently the utils.cpp script is hard coded to state confidence intervals at a precision of exactly 10 decimal places, which is unhelpful for limits below that precision (and also for much larger numbers than this). It would be useful if this was either easily configurable (I had to modify the Utils::calcNsubdigits funtion that I print below) or round to a sensible range depending on the interval.

```
int Utils::calcNsubdigits(double value, int sigdigits)
{
	if ( value==0 ) return 1;
	double myvalue = value;
	int count = 0;
	for (; fabs(value)<pow(10.,sigdigits-1); value *= 10)
	{
		if ( count==10 ) break;
		count++;
	}

	// do it again to catch a rounding issue: 9.97 at 2 digit
	// precision gives count=1 above, but we want count=0 to
	// get "10" instead of "10.0"
	value = TString(Form("%.*f",count,myvalue)).Atof();
	if ( value==0 ) return 1;
	count = 0;
	for (; fabs(value)<pow(10.,sigdigits-1); value *= 10)
	{
		if ( count==10 ) break;
		count++;
	}
	return count;
}
```

Cheers,

Ifan

**Comment by tmombaecher** [comment]
@matthewkenzie do you remember why it was done with this cutoff? Could be done in a more clever way, can't it?

**Comment by matthewkenzie** [comment]
Yes it can be done in a more clever way but I would also remember that most minimiser (Minuit included) prefer working with parameters of order 1. So you are much better off expressing your parameters using a scale factor that gets them nearer one. For which then 10 decimal places is sufficient.
