### ISSUE TITLE
Breaks with ROOT v6.30.04

### ISSUE THREAD

**Issue by kdebruyn** [gammacombo/gammacombo#251]
(1) The development branch no longer compiles with ROOT v6.30.04, the current default. Issues:
- RooMinuit has been replaced with RooMinimizer (affects Utils.cpp and PDF_Abs.cpp)
- RooMinimizer does no longer have the function setNoWarn()
- RooFormula.h no longer exists (affects tutorial only)
- RooAbsArg does no longer provide the operator= (affects RooBinned2DBicubicBase.cpp)
Replacing/removing these functions allows you to compile successfully

Patches credit to @manuelschiller 
[0001-RooMinuit-has-been-deprecated-use-RooMinimizer-inste.patch](https://github.com/gammacombo/gammacombo/files/14387212/0001-RooMinuit-has-been-deprecated-use-RooMinimizer-inste.patch)
[0002-RooBinned2DBicubicBase-remove-operator.patch](https://github.com/gammacombo/gammacombo/files/14387213/0002-RooBinned2DBicubicBase-remove-operator.patch)
[0003-tutorial_dataset_build_workspace-remove-unused-inclu.patch](https://github.com/gammacombo/gammacombo/files/14387215/0003-tutorial_dataset_build_workspace-remove-unused-inclu.patch)

(2) The tutorial no longer runs as it should. The code crashes at step MethodProbScan::scan1d() with error message "Error in <ROOT::Math::Fitter::SetFCN>: FCN function has zero parameters".  For the tutorial this message makes sense as there are no other parameters that need to be minimised during the parameter scan. My hypothesis: in older ROOT versions the m.migrad() step did not complain about this exception/corner case, but in the latest versions it cannot handle the trivial case anymore and aborts execution.

**Comment by kdebruyn** [comment]
Regarding (2):
- The order between setting parameters constant and initialising the RooMinimizer matters. Current code first sets constant and then initialises, which leads to the error message. The other way around is fine.
- Skipping the migrad step when not needed will not fill the RooFitResult and thus does not allow to obtain a value from minNll().

**Comment by matthewkenzie** [comment]
should now be resolved with https://github.com/gammacombo/gammacombo/pull/254 (and a couple of others). will make a new release imminently.
