### ISSUE TITLE
Grid support

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#27]
Enable direct submission of batch jobs to the grid.

**Comment by matthewkenzie** [comment]
This is a desirable enhancement however is not really necessary for almost all use cases. We already have batch support enabled which will submit via the condor system (no other batch systems are currently supported) and does all (or most of) the bookkeeping internally.

I would say this is probably sufficient for 99.99% (if not all) use cases.

Grid support is only really needed for hugely expensive scans, i.e. nD FC scans for complex fits. The interface here is not trivial though as users from different experiments have different interfaces with the Grid. In the case of LHCb this happens via DIRAC but even then direct interaction with DIRAC is not recommended and one has to go through `ganga` which adds another level of complexity.

Consequently, I am going to close this issue. I don't think we need it.
