### ISSUE TITLE
Pass plotting options and PDF init info via config file, e.g. json

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#28]
To improve the "customizability" and to reduce the amount of command line options.

**Comment by matthewkenzie** [comment]
I was thinking a little bit about this. Would there be a single plotting options file or would it be better to separate them and have e.g. one options file for 1D plots and one options file for 2D plots? It's also slightly unclear, at least to me, exactly which classes would talk to the options files. Some of the plotting options are set in core/src/OneMinusClPlotAbs.cpp, some in core/src/OneMinusClPlot.cpp (for 1D) and some in core/src/OneMinusClPlot2D.cpp (for 2D). There is also some python modules for "dressing" plots once they have been stored in a root file (scripts/dressPlot.py, scripts/plotModuleExample.py) to make for example plots like the one attached.
[VubVcb_update.pdf](https://github.com/gammacombo/gammacombo/files/81170/VubVcb_update.pdf)

**Comment by KonstantinSchubert** [comment]
I guess the nice thing about having an option file is that any class that needs some information from it can read it? 
And I guess having a single options fill (with different sections) is easier to manage for the user than having two or more.
Just my 0.02.

**Comment by KonstantinSchubert** [comment]
I changed the title a bit. 

There are lots of mandatory init calls for the PDF_Datasets which map the argsets

**Comment by tmombaecher** [comment]
Actually we would want to hand the options from the options file down to the OptParser, since about every class reads from it. 
So we might want to parse the file into a commandline string.
This can then be readout with the `parseArguments` function of the OptParser.

I would also go for the possibility of giving multiple optionsfiles, since one might want to split plotting and computing options

**Comment by matthewkenzie** [comment]
Now resolved with mpl tools - although there are still duplicates here that need smoothing out.
