### ISSUE TITLE
Update ROOT dependency to ROOT6

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#29]
Is this desired? In my opinion it is :)

**Comment by matthewkenzie** [comment]
Yes that would be nice but it would be best to keep compatibility with root
5 is possible.

**Comment by KonstantinSchubert** [comment]
You're right about keeping compatibility.

**Comment by KonstantinSchubert** [comment]
GammaCombo seems to be working quite nicely with ROOT6
