### ISSUE TITLE
PDF ids start with one (not with zero) in the tutorials.

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#36]
I noticed that both existing tutorials do not add a PDF with id zero. For example in the default tutorial:

	gc.addPdf(1, new PDF_Gaus("year2013","year2013","year2013"),   "1D Gaussian (a_{obs} = -0.5)");
	gc.addPdf(2, new PDF_Gaus("year2014","year2014","year2014"),   "1D Gaussian (a_{obs} =  1.5)");
	gc.addPdf(3, new PDF_Gaus2d("year2013","year2013","year2013"), "2D Gaussian (a_{obs}, b_{obs})");
	gc.addPdf(4, new PDF_Circle("year2013","year2013","year2013"), "circle (a_{obs}, b_{obs})");

This is inconsistent with the combiner objects, where an empty combiner with id zero is added.
Also the gammacombo engine seems to use the PDF id as an index:

	void GammaComboEngine::addPdf(int id, PDF_Abs* pdf, TString title)
	{
		...
		this->pdf[id] = pdf;
	}

Is there a reason for this or is the zero'th entry of the pdf vector in the gammacombo engine left to be zero?

**Comment by matthewkenzie** [comment]
The reason it's like this is that it is easy to imagine an empty
combination (id=0) but not really easy to imagine an empty pdf. I would
rather leave it as is in case it breaks everyones executables unless there
is a really good reason to change.

**Comment by matthewkenzie** [comment]
Ah. I think I misunderstood your question. I would leave the current tutorials as they are. Do which ever you prefer for your own "Datasets" tutorial

**Comment by KonstantinSchubert** [comment]
Sorry, I am not sure if I got you right. 

Is there anything that speaks against assigning the id zero to the first PDF that is added?

Is it because zero somehow stands for: Empty PDF/Combiner and therefore we avoid it?
From my point of view, it is  a bit strange to start an enumeration at index 1. At some point someone might wonder why ` *(this->pdf[0]) ` gives a segfault in the gammacombo engine.

**Comment by matthewkenzie** [comment]
It is indeed because zero in principle stands for empty but there is no
reason why you can't assign the first PDF to id 0.

**Comment by KonstantinSchubert** [comment]
Alright, it really seems the Gammacombo engine doesn't expect the pdf vector to be sequentially filled. 
So it really doesn't matter. :)
