### ISSUE TITLE
Find a clean way for organizing the tutorials and update Cmake config so they all compile without edits.

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#37]
In the `tutorial` folder, there is a subfolder called `cartesian` that contains another tutorial complete with `CMakeLists.txt` etc. However with the current cmake setup, it seems like it is not being compiled.

I was planning to use the same setup for my `datasets_tutorial`.

Alternatively, we could also put all tutorials (the default one, the cartesian and my new one) in a folder called "tutorials".

I am a bit unsure how to organize all of this since I don't have a lot of experience with cmake.

**Comment by matthewkenzie** [comment]
See p22 of the GammaComboManual.pdf .

One is required to cp -r this directory one level up (so that cartesian
lives in the same directory as tutorial). I agree this is not a great
solution and we should reconfigure the compilation so that within the
tutorial directory there can be several different tutorials (or something
similar). For now the quickest solution is to make a new tutorial_datasets
folder for it or something like that.

**Comment by KonstantinSchubert** [comment]
Okay, I'll just commit the dataset_tutorial folder into the base directory
besides the tutorial folder and add it as a combination.

We should probably figure out a cleaner way before release. So I suggest
leaving this issue open?

**Comment by matthewkenzie** [comment]
Agree

**Comment by KonstantinSchubert** [comment]
Maybe it would be best to treat the default tutorial, the cartesian tutorial and the dataset_tutorial as one single `combiner` (instead of 3). This would mean putting all three of them into a folder that contains the cmake and defines the combiner. Something like this:

tutorial <- this is the new combiner project
    |_____________________________________________________________
    |                                              |                              |                                            |
CMakeLists.txt                 main_tutorial/           cartesian_tutorial/             datasets_tutorial/    <-- these all get compiled when the combiner project gets compiled.

**Comment by matthewkenzie** [comment]
I think this could be a good solution. They could each have a separate
executable in "main" but still have the same folder directory.

**Comment by KonstantinSchubert** [comment]
Ah, I think that's not what I mean, I was thinking of leaving them in separate subfolders.

You're saying we should merge the include, src and main directories between the tutorials?
In fact what you're suggesting has the advantage  that it would closely mimic the style of the subpackages. Could be a good solution.

**Comment by KonstantinSchubert** [comment]
I just realized how much the documentation relies on the "cartesian" combiner to be in the subdirecotry tutorial/cartesian.
It uses this to explain how to add a combiner, edit the cmake list etc...

> The following steps describe how to create the source files needed for a new combiner.
> The complete solution is contained in the directory tutorial/cartesian, so the
> quick way to get it run is to just copy this directory one level up to where the other
> combiner directories live.
> [...]

I think this is very nicely written and useful. I therefore propose we move the stuff belonging to the cartesian tutorial back into its own subfolder.  Sorry for the noise...

What do the others think?

**Comment by matthewkenzie** [comment]
Isn't it simpler to change the manual such that all tutorial/cartesian are
simply replaced? I haven't looked at this for a while so if that isn't the
case then maybe we should consider adjusting the cmake files so that one
can compile the whole lot together?

**Comment by KonstantinSchubert** [comment]
The point of the cartesian tutorial seems to be that the user learns how to edit the cmake configuration in order to add a new combiner.

In the current constellation, the cartesian stuff is part of the tutorial-combinert. Therefore it isn't able to serve its purpose of demonstrating how to add a new combiner.

**Comment by matthewkenzie** [comment]
This has now been resolved but so long ago I can't find the relevant pull request for it. The `cartesian.cpp` now lives as a separate executable in `tutorial/main`
