### ISSUE TITLE
Integrate coverage test code

### ISSUE THREAD

**Issue by matthewkenzie** [gammacombo/gammacombo#41]
Need to integrate the code which performs the coverage test. This currently exists in a private branch and should be ready to merge soon. Some other outstanding issues:

- Coverage plots currently have default range 0:180 for the POI (only relevant for angles in this range) so should be updated for any variable
- Should be able internally to fit the output p-value distributions to assess what the coverage correction should be
- Need to find out if the 1-CL plots are correctly adjusted for a given coverage correction (should this be analytical from a fit function or directly from the histogram)
- Need to make sure this works with the batch submission system

**Comment by KonstantinSchubert** [comment]
The private branch has now been merged to reduce divergence.
But it will be merged again once the work on it is finalized.

**Comment by KonstantinSchubert** [comment]
I think this can be closed?
