### ISSUE TITLE
Assure that the datasets classes give good results for B2MuMu

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#60]

**Comment by mschlupp** [comment]
turns out not to be an easy one.
ProbScan results not properly propagated to the plugin scan. First test yields results that are way off.

**Comment by mschlupp** [comment]
Titus, any plans to do this? Else probably close the issue

**Comment by tmombaecher** [comment]
Will do some final tests on B24mu with the merged master branch and then close this issue. A prefinal version of the datasets_dev branch yielded perfect compatibility with the results reported in the AnaNote. They used the L&S package from CMS.

I don't think it is necessary to do the B2mumu checks anymore.

**Comment by matthewkenzie** [comment]
Would like to close some old outdated issues and this seems to fit the bill. I believe this is not really necessary anymore especially given the recent advancements made by @tmombaecher in particularly !187 (and later fixes). Suggest to close this Issue soon.

**Comment by tmombaecher** [comment]
Yes, we have been able to prove the method externally with RooStats, which should serve as a proper cross check. We'll be able to reuse the tool for B2mumu.
