### ISSUE TITLE
Make PDF_Datasets_Abs a self-sustained default that does not need to be implemented

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#61]
In the current iteration we require users to write a pdf class that inherits from PDF_Datasets_Abs.
After discussion with Max we agreed that it makes sense to provide a sensible and functioning default implementation of this class. 

Users that need to tinker with the fit procedure can extend it via inheritance.

**Comment by mschlupp** [comment]
Yes, that's something I had in mind for quite some time. Then, go ahead an rename ```PDF_Datasets_Abs``` to ```PDF_Datasets```.
I'll then implement the custom fit method from the b2mm package in the ```PDF_DatasetTutorial``` in order to demonstrate how flexible the framework is. 
Thanks, Konstantin.
