### ISSUE TITLE
Command line option for non-linear interpolations

### ISSUE THREAD

**Issue by mschlupp** [gammacombo/gammacombo#66]
What is the opinion about a command line option that enables non-linear interpolation, especially in the OMCL plot? I think, in the OMCL plot, the same interpolation should be plotted that was used to calculate the confidence levels. Therefore, the interpolation method used to calculate the confidence levels should be known to the respective scanner class as well as the OMCL plot class. We could use the already implemented---I suspect linear---interpolation as default and add the possibility for e.g. cubic splines.

**Comment by KonstantinSchubert** [comment]
* 100% agree on this:  I think, in the OMCL plot, the same interpolation should be plotted that was used to calculate the confidence levels.

* If we want to offer anything besides linear and cubic interpolation we become dependent on TMVA, right? Should we therefore restrict ourselves to these two?

**Comment by mschlupp** [comment]
I'm totally fine with linear and cubic splines.

**Comment by matthewkenzie** [comment]
I'm not entirely sure what the latest status is with interpolation. I know @tmombaecher has added some stuff for this. Perhaps we can now resolve this issue?

**Comment by tmombaecher** [comment]
No, in principle there are a few things to this issue:
1) what interpolation is used for the boundary computation. We use quadratic interpolation with 3-5 points (depending on how close we are to the scan range boundary) and if that fails a linear interpolation. I don't see why one would want to specify this with options. At least I haven't seen this really fail. If we have such a case, we could reopen that issue.
2) plotting the same interpolated graph as is used in the calculation of the CI boundaries. That's a good point, but as we only interpolate through a part of the scanpoints, this does not make much sense. And to be fair, the difference is hardly visible.

So I would say we can close this issue.

**Comment by tmombaecher** [comment]
Actually Fionn Bishop noticed that the quadratic interpolation was actually buggy (and thus always fell back to linear interpolation). Fixed this in #207 and made some sanity checks. Looks good across the tutorial cases (checked with datasets/combiner case, prob/plugin)!

**Comment by matthewkenzie** [comment]
This is all looking very nice and good that we are managing to close a few issues and that someone has had a good look at the control plots which haven't been looked over for a while.

One little thing I noticed is that `MethodDatasetsPluginScan.cpp` has a `drawPlots` member but this seems fairly defunct as we can just use `arg->controlplots`?
