### ISSUE TITLE
Avoid repeating identical fits on different machines when doing pluginbatch.

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#67]
When running pluginbatch, we read the free fit result from the workspace, but the constrained fit to data (where the scan parameter is fixed and the nuisance parameters are free) is repeated for each batch job. This increases resource usage and the chance of an unnoticed fit failure. 

I know this affects the datasets stuff, not sure if the normal gammacombo plugin scans are also affected.

I propose that before doing the plugin scans, we first do a proper prob scan. This means that all the fits to data are being performed. For each scan point, we also save the values of the nuisance parameters to the tree. 

Then, the `pluginbatch` jobs do not repeat the fits to data, instead they take the likelihood values and nuisance parameter values (for toy generation)  from the tree that was created during the prob scan. The root file containing this tree needs to be uploaded to the batch machines for this to work.

**Comment by mschlupp** [comment]
As discussed, this is implemented in the B2mm combination

**Comment by KonstantinSchubert** [comment]
How would you like me to proceed with this, it at all? 

Would you like to copy as much code from the B2mm combination as possible or would you be okay with a re-implementation?

Would you rather do this before or after we get the B2mm combination to run on the datasets_dev branch?

**Comment by mschlupp** [comment]
>  How would you like me to proceed with this, it at all?
You can try to figure out which of the features from the B2mm DataSets PDFs (esp PDF_B_MuMu) has to be implemented in the PDF_Datasets classes. E.g. the part which this issue is about. 

> Would you like to copy as much code from the B2mm combination as possible or would you be okay with a re-implementation?
No re-implementation without a baseline test!! and we need a test, which is not as complicated as B2mm combination. Probably we can discuss about a more complicated toy, which we use as a baseline test after we showed the code works with B2mm combination.

> Would you rather do this before or after we get the B2mm combination to run on the datasets_dev branch?
IMO, this can be done in parallel, esp. migrating code from the PDF_B_MuMu to PDF_Dataset.

**Comment by KonstantinSchubert** [comment]
I tried to summarize the current call interface for the datasets stuff  in gammacombo and how it could be improved. It is related to this issue. Let me know what you think.
https://docs.google.com/document/d/15WCzIpb2ZriQ-5i0Cz65MK5rZfpb0I21bV-F4d67vEA/edit?usp=sharing

**Comment by KonstantinSchubert** [comment]
This should all be fixed as of 2d0c95c1f48
