### ISSUE TITLE
Compile errors with tutorial

### ISSUE THREAD

**Issue by mschlupp** [gammacombo/gammacombo#69]
When I try to compile the Datasets Tutorial, I get errors:

<img width="692" alt="screen shot 2016-02-15 at 16 50 33" src="https://cloud.githubusercontent.com/assets/11273097/13053349/54282288-d404-11e5-81de-49add75d4cd7.png">

I can't really see what is wrong with the syntax and wonder why I got these errors.

Might there be an issue with Linux/MacOS compilers?
I use:
```
llvm-gcc --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

We should:
A) figure out what's wrong (best)
B) revert changes to minimal working example (e.g. using ROOT?)

**Comment by KonstantinSchubert** [comment]
What is your compiler version?

**Comment by KonstantinSchubert** [comment]
Can you try adding `#include <random>` ?

**Comment by mschlupp** [comment]
including `random` doesn't help.

**Comment by mschlupp** [comment]
Compilation seems to work with: 

Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Not sure which exact version might be needed for Apple's Xcode (LLVM/clang)
