### ISSUE TITLE
Implement the "Asymptotic Formulae" for improved precision in the prob scan

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#82]
The paper Asymptotic formulae for likelihood-based tests of new physics by Glen Cowan, Kyle Cranmer, Eilam Gross, Ofer Vitells outlines formulae that approximate the distribution of the delta log likelihood test statistic in the presence of physical boundaries.

https://arxiv.org/abs/1007.1727

These are basically more sophisticated versions of the TMath::Prob formula.

I propose that, as a first step, we introduce a new helper class where we implement these functions. We can then use this class to offer command line options for the plugin scan which turn on these improved approximations.

**Comment by mschlupp** [comment]
I would probably save these enhancement for students, who should learn to use the package? I personally think these are only second order corrections, as we use the plugin scan to quote nominal results.

**Comment by tmombaecher** [comment]
This is actually done now with #183, a we need them anyhow for a meaningful CLs.
For the prob scan the asymptotic formulae using the test statistics `t` and `q` are implemented, while the plugin scan with the `--prange` argument will effectively apply `t~` and `q~` with potentially additional similar boundary treatment for nuisance parameters
