### ISSUE TITLE
Critical bug in MethodDatasetsPluginScan

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#83]
Since about PR https://github.com/gammacombo/gammacombo/commit/5563426e405aafe4a87941175c4b7b8a84505639 ,
we do no longer repeat the fit-to-data-with-fixed-scanpoint before the fits to the toys in the PLUGIN algorithm.

This means that line 696 https://github.com/gammacombo/gammacombo/blob/datasets_dev/core/src/MethodDatasetsPluginScan.cpp#L696 cannot perform its function any more: Because there was no  fit-to-data-with-fixed-scanpoint before, this does not any more store the PLUGIN values of the nuisance parameters.

Therefore, the PLUGIN values of the nuisance parameters are not set correctly when simulating toys for the PLUGIN scan.

I propose we fix this by implementing the `getParevolPoint` method from the `MethodPluginScan`. and by calling it at this point. However, I would perfer to use the index of the scan point instead of the value of the scan point as argument. Therefore we could call the method `getParevolPointByIndex(int index)`

During the PROB scan we can save snapshots of the nuisance parameters (or of all parameters) and enumerate these snapshots by adding the scan point index to their name. These snapshots would need to be stored in the root file which is saved from the PROB scan. We can then load these snapshots in the `getParevolPointByIndex` method.

This should be reasonably fool proof and also easy to do.

**Comment by KonstantinSchubert** [comment]
There is now a PR: https://github.com/gammacombo/gammacombo/pull/84

**Comment by mschlupp** [comment]
Why do the lines 679 to 689 not protect the code?

this only results in a bug, when the input file does not correspond to the actual scan, which I run into while testing the code?

What or am I missing something?

**Comment by mschlupp** [comment]
The trick is suppose to work like this:

if there is an external profile likelihood evolution file given (which contains all the values of the nuisance parameters after a fit to the dataset with fixed POI), then it simply loads these values, if there is no external file given only the probscan is performed yielding the input file (external profile likelihood evolution) for the plugin scan.

**Comment by KonstantinSchubert** [comment]
Okay, I see the issue now: I was not passing the full set of parameters to the PDF when initializing the PDF. In fact, I was passing only the parameter of interest, and no nuisance parameters.
As a result, it did not load all parameters as intended.

I will fix this by passing all parameters, especially in the tutorial.
