### ISSUE TITLE
Use a graph instead of a histogram to store the p-Value

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#86]
In MethodAbsScan, we use a histogram called hCL to store the mapping of scan points to p-Values.

A histogram is by design not suitable for this as it assigns values to ranges, not to points. This results in problems.

Therefore, I propose that we use a graph to store the mapping, or two vectors of equal length. 

If possible we should move away from using ROOT objects though.

**Comment by KonstantinSchubert** [comment]
it seems that the scan values (== scan points!) are in the middle of the histogram bins,
and the scan range seems to delimit the left edge of the first bin until the right edge of the last bin
This means that the first scan point is half a bin above the lower edge of the passed range, and the last scan point
is half a bin below the right passed edge. This means if we pass a range of 0-10 and 10 scan points, we get scan points
0.5, 1.5, 2.5, ... and so on.
The question is if we want to keep this behaviour or not.
I suggest that we change it, since it is very unintuitive that the zero hypotheis is never actually tested when passing the range 0-10

**Comment by mschlupp** [comment]
In principle I agree on what you propose! 
This will be a major change, though. On the other hand, the half-bin-width shift doesn't change numerical results, as far as I know. You always have the numerical values in the toy-tree. I am not exactly sure if the hCL histogram is used to really calculate results. I avoided hCL as part of the debugging in the B2mm combination.

**Comment by matthewkenzie** [comment]
This is indeed a major overhaul and would require lots of lines to change in lots of place. There is no problem with what is done now and the common way to deal with this is to expand the range slightly to incorporate any other points (you can then plot in a different range if required). Going to close this.
