### ISSUE TITLE
Remove `using namespace` directive

### ISSUE THREAD

**Issue by KonstantinSchubert** [gammacombo/gammacombo#87]
This is a proposal. I think we should remove them because the clear namespacing improves readability and avoids conflicts.

**Comment by mschlupp** [comment]
Totally agree! And I am follow this narrative in the code I write (at least I hope). This is, however, a matter of taste and has been introduced by Moritz at the very start of the package. 
Should in principle be easy to change, but might take a bit of time!

**Comment by mschlupp** [comment]
for @matthewkenzie  to close or assign :)

**Comment by matthewkenzie** [comment]
I am happy for someone to change as I agree it makes it easier to read the code however this has been there since a long time and is not something I consider urgent. Please feel free @mschlupp @KonstantinSchubert to change if you would like to.

**Comment by matthewkenzie** [comment]
It is not totally resolved and I don't think that much of a problem.
